### ISSUE TITLE
Replays of latest games will not start

### ISSUE THREAD

**Issue by MRLB** [hubsif/kodi-tk_bbl#10]
Unfortunately the gamereports and the full replays will not start anymore.
For example Bayreuth - Braunschweig or the Euroleague match of Bamberg.

The replays from Wednesday and the match days before work.

Thank you for the greats addon.

**Comment by MRLB** [comment]
All gamereports/Replays of all matches of the fifth matchday does not work. Livematches worked yesterday.

**Comment by hubsif** [comment]
This is due to errorneous data from the webservice. I still have the old mobile phone app installed (1.2.4 on iOS), those videos don't run there either.
Seems like the Telekom (or rather her content provider) only concentrates on her new webservice, not caring about people with older app versions.

So, there's not much I can do here, besides getting a new addon version based on the new webservice running.
